// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grywqokiqktwrsbikzlv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyeXdxb2tpcWt0d3JzYmlremx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NzUxNjUsImV4cCI6MjA2MTI1MTE2NX0.fpPL9yDM_ttX9tK8fR-mmuIJueW4P74d5QFG1RtlwQk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    storage: window.localStorage,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});